import { eq, and } from "drizzle-orm";
import { getDb } from "./connection";
import { appConfigs } from "@db/schema";

export async function findAllAppConfigs() {
  const db = getDb();
  return db.select().from(appConfigs).where(eq(appConfigs.isActive, true));
}

export async function findAppConfigByKey(key: string) {
  const db = getDb();
  const rows = await db
    .select()
    .from(appConfigs)
    .where(and(eq(appConfigs.key, key), eq(appConfigs.isActive, true)))
    .limit(1);
  return rows[0] || null;
}

export async function seedAppConfigs() {
  const db = getDb();
  const existing = await findAllAppConfigs();
  if (existing.length > 0) return;

  const apps = [
    {
      key: "tiktok",
      name: "TikTok Global",
      aid: 1233,
      appName: "musical_ly",
      package: "com.zhiliaoapp.musically",
      versionCode: "350804",
      versionName: "35.8.4",
      channel: "googleplay",
      typeCodesJson: JSON.stringify([3635, 3637, 3634, 3734, 3532]),
      domainsJson: JSON.stringify([
        "api16-normal-c-useast2a.tiktokv.com",
        "api16-normal-v6.tiktokv.com",
        "api-t2.tiktokv.com",
        "api19-normal-c-useast2a.tiktokv.com",
        "api21.tiktokv.com",
        "api-h2.tiktokv.com",
        "api22-normal-c-alisg.tiktokv.com",
      ]),
      needsProxy: true,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "tiktok",
    },
    {
      key: "tiktok_web",
      name: "TikTok Web",
      aid: 1459,
      appName: "tiktok_web",
      package: "tiktok_web",
      versionCode: "1",
      versionName: "1.0",
      channel: "tiktok_web",
      typeCodesJson: JSON.stringify([3532, 3635, 3733, 3631, 3637, 3634, 3734, 3132]),
      domainsJson: JSON.stringify(["www.tiktok.com", "us.tiktok.com", "www.capcut.com"]),
      needsProxy: true,
      webEndpoint: true,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "tiktok",
    },
    {
      key: "tiktok_lite",
      name: "TikTok Lite",
      aid: 1340,
      appName: "trill",
      package: "com.zhiliaoapp.musically.go",
      versionCode: "350804",
      versionName: "35.8.4",
      channel: "googleplay",
      typeCodesJson: JSON.stringify([3132, 3631, 3632, 3634, 3637, 3733, 3734, 3530, 3635]),
      domainsJson: JSON.stringify([
        "api16-normal-c-useast2a.tiktokv.com",
        "api16-normal-v6.tiktokv.com",
        "api16-normal-v4.tiktokv.com",
        "api19-normal-c-alisg.tiktokv.com",
      ]),
      needsProxy: true,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "tiktok",
    },
    {
      key: "douyin",
      name: "Douyin",
      aid: 1128,
      appName: "aweme",
      package: "com.ss.android.ugc.aweme",
      versionCode: "290100",
      versionName: "29.1.0",
      channel: "update",
      typeCodesJson: JSON.stringify([3532, 3635, 3637, 3634]),
      domainsJson: JSON.stringify([
        "api.amemv.com",
        "api3-normal-c-lf.amemv.com",
        "is.snssdk.com",
        "ib.snssdk.com",
        "aweme.snssdk.com",
        "verify.zijieapi.com",
      ]),
      needsProxy: true,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "douyin",
    },
    {
      key: "douyin_web",
      name: "Douyin Web",
      aid: 1988,
      appName: "douyin_web",
      package: "douyin_web",
      versionCode: "1",
      versionName: "1.0",
      channel: "douyin_web",
      typeCodesJson: JSON.stringify([3635, 3532, 3734]),
      domainsJson: JSON.stringify(["us.tiktok.com", "www.tiktok.com"]),
      needsProxy: true,
      webEndpoint: true,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "douyin",
    },
    {
      key: "capcut",
      name: "CapCut",
      aid: 3006,
      appName: "vicut",
      package: "com.lemon.lvoverseas",
      versionCode: "17700200",
      versionName: "17.7.0",
      channel: "googleplay",
      typeCodesJson: JSON.stringify([3532, 3733, 3635, 3637, 3634]),
      domainsJson: JSON.stringify([
        "api2-16-h2.musical.ly",
        "api16-normal-c-useast1a.tiktokv.com",
        "api16-normal-c-useast2a.tiktokv.com",
        "api16-normal-v4.tiktokv.com",
        "passport-api.capcut.com",
        "passport-api.capcutapi.com",
      ]),
      needsProxy: true,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "capcut",
    },
    {
      key: "pipix",
      name: "Pipix",
      aid: 1319,
      appName: "super",
      package: "com.sup.android.superb",
      versionCode: "620",
      versionName: "6.2.0",
      channel: "update",
      typeCodesJson: JSON.stringify([3532, 3635, 3637, 3634]),
      domainsJson: JSON.stringify([
        "api5.pipix.com",
        "api3.pipix.com",
        "is-hl.snssdk.com",
        "aweme.snssdk.com",
        "ib.snssdk.com",
      ]),
      needsProxy: false,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "pipix",
    },
    {
      key: "toutiao",
      name: "Toutiao",
      aid: 13,
      appName: "news_article",
      package: "com.ss.android.article.news",
      versionCode: "9500",
      versionName: "9.5.0",
      channel: "update",
      typeCodesJson: JSON.stringify([3635, 3532, 3634]),
      domainsJson: JSON.stringify([
        "verify.zijieapi.com",
        "api.amemv.com",
        "api3-normal-c-lf.amemv.com",
      ]),
      needsProxy: false,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "toutiao",
    },
    {
      key: "xigua",
      name: "Xigua Video",
      aid: 32,
      appName: "video_article",
      package: "com.ss.android.article.video",
      versionCode: "7500",
      versionName: "7.5.0",
      channel: "update",
      typeCodesJson: JSON.stringify([3635, 3532, 3634]),
      domainsJson: JSON.stringify([
        "api3-normal-c-lf.amemv.com",
        "api.amemv.com",
        "www.ixigua.com",
      ]),
      needsProxy: false,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "xigua",
    },
    {
      key: "lemon8",
      name: "Lemon8",
      aid: 2239,
      appName: "musical_ly",
      package: "com.zhiliaoapp.musically",
      versionCode: "350804",
      versionName: "35.8.4",
      channel: "googleplay",
      typeCodesJson: JSON.stringify([3634, 3635, 3637, 3734, 3532]),
      domainsJson: JSON.stringify([
        "api77-normal-c-useast1a.tiktokv.com",
        "lemon8-api.tiktokv.com",
        "verify-sg.tiktokv.com",
        "api-h2.tiktokv.com",
        "api16-normal-c-useast1a.tiktokv.com",
      ]),
      needsProxy: true,
      webEndpoint: true,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "lemon8",
    },
    {
      key: "tiktok_voice",
      name: "TikTok Voice Call",
      aid: 1233,
      appName: "musical_ly",
      package: "com.zhiliaoapp.musically",
      versionCode: "350804",
      versionName: "35.8.4",
      channel: "googleplay",
      typeCodesJson: JSON.stringify([3635, 3731, 3532]),
      domainsJson: JSON.stringify([
        "api16-normal-v6.tiktokv.com",
        "api16-normal-c-useast2a.tiktokv.com",
        "www.tiktok.com",
      ]),
      needsProxy: true,
      webEndpoint: false,
      voiceEndpoint: true,
      unsignedMobile: false,
      category: "voice",
    },
    {
      key: "helo",
      name: "Helo",
      aid: 1180,
      appName: "musical_ly",
      package: "com.ss.android.ugc.helo",
      versionCode: "4500",
      versionName: "4.5.0",
      channel: "googleplay",
      typeCodesJson: JSON.stringify([3631, 3632, 3634, 3637, 3733, 3734]),
      domainsJson: JSON.stringify([
        "api16-normal-v4.tiktokv.com",
        "api16-normal-c-useast2a.tiktokv.com",
      ]),
      needsProxy: true,
      webEndpoint: false,
      voiceEndpoint: false,
      unsignedMobile: false,
      category: "helo",
    },
  ];

  for (const app of apps) {
    await db.insert(appConfigs).values(app);
  }
}
